# Generated by Django 3.0.2 on 2021-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=16)),
                ('father_name', models.CharField(max_length=50)),
                ('father_citizen_number', models.CharField(max_length=50)),
                ('grand_father_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('t_zone', models.CharField(max_length=50)),
                ('t_district', models.CharField(max_length=50)),
                ('t_village', models.CharField(max_length=50)),
                ('t_ward_no', models.IntegerField()),
                ('t_tole', models.CharField(max_length=50)),
                ('t_house_no', models.IntegerField()),
                ('p_zone', models.CharField(max_length=50)),
                ('p_district', models.CharField(max_length=50)),
                ('p_village', models.CharField(max_length=50)),
                ('p_ward_no', models.IntegerField()),
                ('p_tole', models.CharField(max_length=50)),
                ('p_house_no', models.IntegerField()),
            ],
        ),
    ]
